services:

  postgres:
    image: postgres:16
    container_name: stickerwall-db
    restart: always
    environment:
      POSTGRES_DB: stickerwall
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stickerwall
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend